# Generated by Django 2.1.1 on 2020-08-13 09:03

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('phone', phone_field.models.PhoneField(blank=True, help_text='Contact Phone number', max_length=31)),
                ('location', models.CharField(default='some location', max_length=100)),
                ('business', models.CharField(default='some business', max_length=100)),
                ('amount', models.IntegerField(default=0)),
                ('customerSignature', models.FileField(blank=True, upload_to='Signatures/')),
                ('status', models.CharField(choices=[('PE', 'Pending'), ('RE', 'Received'), ('RJ', 'Rejected'), ('AP', 'Approved')], default='PE', max_length=2)),
            ],
        ),
    ]
